language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.9

install:
  - make
  - pip install poetry

script:
  - python --version
  - poetry install
  - make tests

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/55cf16b611593edcb09d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
